---
# tasks file for cron

- name: Manage system crontab.
  copy:
    src=crontab
    dest=/etc/crontab
    owner=root
    group=root
    mode=0644


- name: Install cron config file.
  template:
    src=cron.j2
    dest=/etc/default/cron
    owner=root
    group=root
    mode=0644
  notify:
    - Restart cron.
